apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: frontendissuer
spec:
  tls:
    - hosts:
        - utube.kendoc.vip  # Replace with your cluster DNS name
      secretName: lets-frontend-tls
  rules:
    - host: utube.kendoc.vip # Replace with your cluster DNS name
      http:
        paths:
          - backend:
              service:
                name: frontend-service
                port:
                  number: 80
            path: /
            pathType: Prefix
